version: "2"
services:
  indico-varnish:
    image: eeacms/varnish                                                   
    depends_on:                                                             
      - indico-nginx                                                               
    links:
      - indico-nginx
    ports:                                                                  
        - "8086:6081"                                                       
    environment:                                                            
      BACKENDS: "indico-nginx"                                                     
      BACKENDS_PORT: "80"                                                 
      BACKENDS_PROBE_ENABLED: "false"  
  indico-web:
    build:
        context: ./indico
        args:
            base_url: "http:\\/\\/localhost:8086"
    depends_on:
        - indico-redis
        - indico-postgres
    links:
     - indico-redis
     - indico-postgres
    environment:
     - PGHOST=indico-postgres
     - PGUSER=indico
     - PGPASSWORD=indicopass
     - PGDATABASE=indico
    tmpfs:
        - /opt/indico/tmp:rw,size=787448k,uid=1000
  indico-redis:
    image: redis
  indico-postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=indico
        - POSTGRES_PASSWORD=indicopass
        - POSTGRES_DB=indico
  indico-nginx:
    image: nginx
    links:
        - indico-web
    volumes:
        - ./nginx:/etc/nginx/conf.d/
    volumes_from:
        - indico-web

